# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v -o ${RUNNER_TEMP}/silkroad
    - name: Test
      run: go test -v ./...

    - name: Output check
      run: |
        ${RUNNER_TEMP}/silkroad -p testdata -o tmptest.dot
        diff <(sort test.dot) <(sort tmptest.dot)
        ${RUNNER_TEMP}/silkroad -p testdata -o tmptest2.dot --ignore-external --go-mod-path .
        diff <(sort test2.dot) <(sort tmptest2.dot)