name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: |
          CGO_ENABLED=0 go build -o ${RUNNER_TEMP}/silkroad
      - run: |
          gh release create ${VERSION} --title "Silkroad ${VERSION}" --generate-notes
          gh release upload ${VERSION} ${RUNNER_TEMP}/silkroad
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
